apiVersion: v1
kind: Service
metadata:
  name: snapshotdb
spec:
  selector:
    app: snapshotdb
  ports:
    - port: 5432
      targetPort: postgres-port
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: snapshotdb
spec:
  selector:
    matchLabels:
      app: snapshotdb
  serviceName: snapshotdb
  replicas: 1
  template:
    metadata:
      labels:
        app: snapshotdb
    spec:
      containers:
        - name: snapshotdb
          image: snapshotdb-image
          env:
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: snapshotdb-pg-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: snapshotdb-pg-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 512Mi