apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: api-image
          env:
            - name: DB_HOST
              value: "snapshotdb"
            - name: DB_NAME
              value: "postgres"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_PORT
              value: "5432"
            - name: ENV
              value: local
            - name: SSL_MODE
              value: disable
          ports:
            - containerPort: 8080